apiVersion: v1
kind: Service
metadata:
  name: version-ci-service
  namespace: technical-test
  labels:
    app: version-ci-app
spec:
  selector:
    app: version-ci-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
